# Generated by Django 6.0.3 on 2026-03-28 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('nom_prop', models.CharField(max_length=100)),
                ('prenom_prop', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('numero_stand', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('validation_code', models.CharField(blank=True, max_length=10, null=True)),
                ('validation_code_expires', models.DateTimeField(blank=True, null=True)),
                ('validation_comment', models.TextField(blank=True, null=True)),
                ('temp_password', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_validation', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='stands.stand')),
                ('valide_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validation',
                'verbose_name_plural': 'Validations',
                'db_table': 'validations',
            },
        ),
    ]
